[project]
name = "inclasscode"
version = "0.1.0"
description = "Code examples for in-class demonstrations for AIST 2110 at Augusta University"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "IPython==9.5.0",
    "ipykernel==6.30.1"
]
