[project]
name = "inclasscode"
version = "0.1.2"
description = "Code examples for in-class demonstrations for AIST 2110 at Augusta University"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "IPython==9.5.0",
    "beautifulsoup4>=4.14.3",
    "ipykernel==7.2.0",
]

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
]

[tool.deptry]
root = ["src"]

[tool.deptry.per_rule_ignores]
DEP001 = ["grades", "grade_formatter"]
DEP002 = ["IPython", "ipykernel"]